default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ang-imob-app_development

test:
  <<: *default
  database: ang-imob-app_test

production:
  <<: *default
  database: ang-imob-app_production
  username: ang-imob-app
  password: <%= ENV['ANG-IMOB-APP_DATABASE_PASSWORD'] %>
